In [1]:
import torch

In [2]:
a = torch.rand(1,2,3)

In [3]:
a

tensor([[[0.8890, 0.4414, 0.5684],
         [0.2574, 0.8244, 0.2390]]])

In [4]:
a.shape

torch.Size([1, 2, 3])

In [5]:
a[0]

tensor([[0.8890, 0.4414, 0.5684],
        [0.2574, 0.8244, 0.2390]])

In [6]:
list(a.shape)

[1, 2, 3]

# Dim = 4

In [9]:
a = torch.rand(2,3,28,28) # （2张图片，3个通道，28*28像素）

In [10]:
a

tensor([[[[0.6490, 0.3479, 0.7928,  ..., 0.2038, 0.7448, 0.7571],
          [0.4962, 0.4547, 0.5481,  ..., 0.4321, 0.7306, 0.6364],
          [0.7162, 0.8416, 0.6739,  ..., 0.5655, 0.7159, 0.8141],
          ...,
          [0.7144, 0.7969, 0.6310,  ..., 0.5410, 0.4326, 0.6524],
          [0.2668, 0.5054, 0.1115,  ..., 0.5311, 0.2743, 0.1620],
          [0.4656, 0.4113, 0.3113,  ..., 0.2569, 0.2168, 0.2920]],

         [[0.4639, 0.8627, 0.2009,  ..., 0.7908, 0.1464, 0.4734],
          [0.2270, 0.5545, 0.6688,  ..., 0.8334, 0.6222, 0.0626],
          [0.0565, 0.0434, 0.8027,  ..., 0.6540, 0.0242, 0.6511],
          ...,
          [0.3793, 0.2650, 0.5004,  ..., 0.2786, 0.0061, 0.9679],
          [0.9192, 0.5676, 0.8694,  ..., 0.2277, 0.1755, 0.5065],
          [0.2163, 0.2080, 0.5568,  ..., 0.9653, 0.1032, 0.3464]],

         [[0.0096, 0.4946, 0.8446,  ..., 0.1567, 0.8062, 0.3761],
          [0.2470, 0.1926, 0.2411,  ..., 0.2125, 0.1252, 0.8604],
          [0.8059, 0.4946, 0.2913,  ..., 0

In [11]:
a.shape

torch.Size([2, 3, 28, 28])

In [13]:
a.numel() # numel是指tensor占用的内存大小

4704

In [14]:
a.dim()

4

In [15]:
a = torch.tensor(1)

In [16]:
a.dim()

0