In [1]:
import torch
import numpy as np

# where

PyTorch 的 where 函数是一个条件语句函数，用于根据给定的条件从两个输入张量中选择元素，并返回一个新的张量。它的语法如下

torch.where(condition, x, y)

下面列举几个常见的应用场景：

1. 条件替换

`where` 函数可以用于条件替换操作。例如，将所有小于某个阈值的元素替换为特定的值，可以使用 `where` 函数。这在图像处理中很常见，例如将图像中所有低于某个亮度阈值的像素替换为黑色。

2. 条件索引

`where` 函数可以用于根据条件选择张量中的元素。例如，选择张量中所有大于某个阈值的元素，可以使用 `where` 函数。这在数据处理中很常见，例如选择异常值或者过大的值。

3. 条件计算

`where` 函数可以用于根据条件计算张量中的元素。例如，对于一个张量，如果它的元素值小于某个阈值，则将其设置为该值的平方，否则将其设置为该值的立方。这在损失函数的计算中很常见，例如对于回归问题，对于预测值和真实值之间的差异进行不同的惩罚。

总之，`where` 函数是一个非常有用的函数，可以让我们在处理数据时更加便捷和灵活。

In [10]:
a = torch.rand(3,3)
b = torch.zeros(3,3)

In [11]:
a

tensor([[0.1874, 0.3390, 0.3112],
        [0.0592, 0.6851, 0.7255],
        [0.3920, 0.6936, 0.6886]])

In [12]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
c = torch.where(a < 0.5, b ,a) # 使用where比使用for快得多
c

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6851, 0.7255],
        [0.0000, 0.6936, 0.6886]])

变量 b 的作用是提供一个零张量，用于替换张量 a 中小于零的元素。

具体来说，b 是一个形状和 a 相同的全零张量，用作 where 函数的第二个输入。在 where 函数中，如果 condition 中的元素值为 True，则选择第一个输入张量 x 中的对应元素，否则选择第二个输入张量 y 中的对应元素。

在本例中，如果 a 中的元素小于零，则选择 b 中的对应元素（即零），否则选择 a 中的对应元素

需要注意的是，b 的值可以是任何张量，只要其形状与 a 相同或者可以通过广播规则进行广播即可。

# gather(收集)

用gpu去查表

In [14]:
prob = torch.randn(4, 10)
idx = prob.topk(dim=1, k=3)
idx

torch.return_types.topk(
values=tensor([[0.5994, 0.5120, 0.2867],
        [1.6230, 1.4252, 1.3826],
        [1.2432, 1.0128, 0.5009],
        [2.2302, 1.4364, 1.4265]]),
indices=tensor([[8, 1, 3],
        [0, 4, 5],
        [9, 3, 2],
        [5, 3, 7]]))

In [15]:
idx = idx[1]
idx

tensor([[8, 1, 3],
        [0, 4, 5],
        [9, 3, 2],
        [5, 3, 7]])

In [16]:
label = torch.arange(10) + 100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [17]:
torch.gather(label.expand(4, 10), dim=1, index=idx.long())
# long()：数据类型转换，转换成torch.int64，因为在视频中tensor创建时默认是浮点型，所以要类型转换

tensor([[108, 101, 103],
        [100, 104, 105],
        [109, 103, 102],
        [105, 103, 107]])