# 激活函数——阶跃函数

![](./img/img3.png)

阶跃函数连续不可导，以前的人们用启发式搜索进行优化。

为解决阶跃函数不可导的问题，人们提出了sigmoid函数

![](./img/img4.png)

# sigmoid函数的求导

![](./img/sigmoid.png)

你可以发现sigmoid函数求导时是不需要另一个新的值的，所以sigmoid就是好啊！

但是当x处于正无穷的时候它的导数接近0，所以参数容易长时间得不到更新，这就是梯度弥散

In [1]:
import torch

In [2]:
a = torch.linspace(-100, 100, 10)  # 从-100到100划分成10个片段
a

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5556,   77.7778,  100.0000])

In [3]:
torch.sigmoid(a) # 这与F.sigmoid是一样的（from torch.nn import functional as F）

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

# tanh

![](./img/tanh.png)

# tanh的求导

![](./img/tanh2.png)

同样的，tanh的导数也不需要新的值

In [4]:
z = torch.linspace(-1, 1, 10)
z

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])

In [5]:
torch.tanh(z)

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])

# ReLu

![](./img/relu.png)

# ReLu函数的求导

![](./img/relu2.png)

首先，它的倒数简单；其次，他很难出现梯度弥撒和梯度爆炸的情况

In [7]:
from torch.nn import functional as F

a = torch.linspace(-1, 1, 10)
torch.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])

In [8]:
F.relu(a)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])