In [1]:
import torch
import numpy as np

# 范数(norm-p)

![](.\img\img1.png)

In [7]:
a = torch.full([8], 1.)
b = a.view(2, 4)
c = a.view(2, 2, 2)

In [8]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [10]:
a.norm(1), b.norm(1), c.norm(1)
# 求1范数

(tensor(8.), tensor(8.), tensor(8.))

In [11]:
a.norm(2), b.norm(2), c.norm(2)
# 求2范数

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [12]:
b.norm(1, dim=1)

tensor([4., 4.])

In [16]:
b.norm(1, dim=0)

tensor([2., 2., 2., 2.])

In [13]:
b.norm(2, dim=1)

tensor([2., 2.])

In [14]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [15]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

In [17]:
c.norm(1, dim=2)

tensor([[2., 2.],
        [2., 2.]])

# 其他一些常见的统计属性

In [19]:
a = torch.arange(8).view(2, 4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [23]:
a.min(), a.max(), a.mean(), a.prod()
# prod:累乘

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [24]:
a.sum()

tensor(28.)

In [26]:
a.argmax(), a.argmin()
# 最大值与最小值的索引（不加dimation就默认是打平后下标）

(tensor(7), tensor(0))

In [28]:
a = torch.rand(4, 10)
a

tensor([[0.1734, 0.5547, 0.4958, 0.3359, 0.2146, 0.3433, 0.6722, 0.1660, 0.8811,
         0.1131],
        [0.1163, 0.6702, 0.6726, 0.7955, 0.8668, 0.4377, 0.6576, 0.0468, 0.1336,
         0.5255],
        [0.8105, 0.4936, 0.4220, 0.1442, 0.0721, 0.3817, 0.0426, 0.3283, 0.0461,
         0.5493],
        [0.0275, 0.2707, 0.5448, 0.0916, 0.8731, 0.5211, 0.4785, 0.8536, 0.0655,
         0.7027]])

In [30]:
a.argmax(dim=1)
# 求每一行的最大值

tensor([8, 4, 0, 4])

In [31]:
a.argmax()

tensor(8)

# dim与keepdim在统计里的作用

In [32]:
a
# 4组照片每张照片的预测值

tensor([[0.1734, 0.5547, 0.4958, 0.3359, 0.2146, 0.3433, 0.6722, 0.1660, 0.8811,
         0.1131],
        [0.1163, 0.6702, 0.6726, 0.7955, 0.8668, 0.4377, 0.6576, 0.0468, 0.1336,
         0.5255],
        [0.8105, 0.4936, 0.4220, 0.1442, 0.0721, 0.3817, 0.0426, 0.3283, 0.0461,
         0.5493],
        [0.0275, 0.2707, 0.5448, 0.0916, 0.8731, 0.5211, 0.4785, 0.8536, 0.0655,
         0.7027]])

In [33]:
a.max(dim=1)

torch.return_types.max(
values=tensor([0.8811, 0.8668, 0.8105, 0.8731]),
indices=tensor([8, 4, 0, 4]))

In [34]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[0.8811],
        [0.8668],
        [0.8105],
        [0.8731]]),
indices=tensor([[8],
        [4],
        [0],
        [4]]))

In [35]:
a.argmax(dim=1, keepdim=True)

tensor([[8],
        [4],
        [0],
        [4]])

# top-k or k-th

In [36]:
a

tensor([[0.1734, 0.5547, 0.4958, 0.3359, 0.2146, 0.3433, 0.6722, 0.1660, 0.8811,
         0.1131],
        [0.1163, 0.6702, 0.6726, 0.7955, 0.8668, 0.4377, 0.6576, 0.0468, 0.1336,
         0.5255],
        [0.8105, 0.4936, 0.4220, 0.1442, 0.0721, 0.3817, 0.0426, 0.3283, 0.0461,
         0.5493],
        [0.0275, 0.2707, 0.5448, 0.0916, 0.8731, 0.5211, 0.4785, 0.8536, 0.0655,
         0.7027]])

In [37]:
a.topk(3, dim=1)
# 每行前三大的概率

torch.return_types.topk(
values=tensor([[0.8811, 0.6722, 0.5547],
        [0.8668, 0.7955, 0.6726],
        [0.8105, 0.5493, 0.4936],
        [0.8731, 0.8536, 0.7027]]),
indices=tensor([[8, 6, 1],
        [4, 3, 2],
        [0, 9, 1],
        [4, 7, 9]]))

In [39]:
a.topk(3, dim=1, largest=False)
# 每行前三小的

torch.return_types.topk(
values=tensor([[0.1131, 0.1660, 0.1734],
        [0.0468, 0.1163, 0.1336],
        [0.0426, 0.0461, 0.0721],
        [0.0275, 0.0655, 0.0916]]),
indices=tensor([[9, 7, 0],
        [7, 0, 8],
        [6, 8, 4],
        [0, 8, 3]]))

In [40]:
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([0.5547, 0.6726, 0.4936, 0.7027]),
indices=tensor([1, 2, 1, 9]))

In [41]:
a.kthvalue(3)
# 第k个value

torch.return_types.kthvalue(
values=tensor([0.1734, 0.1336, 0.0721, 0.0916]),
indices=tensor([0, 8, 4, 3]))

In [42]:
a.kthvalue(3, dim=1)

torch.return_types.kthvalue(
values=tensor([0.1734, 0.1336, 0.0721, 0.0916]),
indices=tensor([0, 8, 4, 3]))

# 比较

In [44]:
a > 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [45]:
torch.gt(a, 0)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [46]:
a != 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [49]:
a = torch.ones(2, 3)
b = torch.randn(2, 3)
torch.eq(a, b)

tensor([[False, False, False],
        [False, False, False]])

In [50]:
torch.eq(a, a)

tensor([[True, True, True],
        [True, True, True]])

In [51]:
torch.equal(a, a)

True