In [1]:
import torch
import numpy as np

# indexing

In [2]:
a=torch.rand(4,3,28,28) #batch_size, chanel, H, W

In [3]:
a[0].shape

torch.Size([3, 28, 28])

In [5]:
a[0,0].shape # 第0张图片第0个通道

torch.Size([28, 28])

In [6]:
a[0,0,2,4] # 第0张图片第0个通道的第二行第四列的像素点

tensor(0.3266)

# select first/last N

In [7]:
a.shape

torch.Size([4, 3, 28, 28])

In [8]:
a[:2].shape # 可以把：理解为->，前两张图片，所以dim1=2

torch.Size([2, 3, 28, 28])

In [9]:
a[:2,:1,:,:].shape # 前两张图片第一个通道的所有图片的数据

torch.Size([2, 1, 28, 28])

In [11]:
a[:2,1:,:,:].shape # 前两张图片，从第一个通道开始到最末尾（G,B通道，所以dim2=2）

torch.Size([2, 2, 28, 28])

In [10]:
a[:2,-1:,:,:].shape # -1表示从末尾索引，-1：也就表示从最后一个索引到最后一个，所以dim2也就=1

torch.Size([2, 1, 28, 28])

## selece by steps(对图片隔着采样)

In [15]:
a[:,:,0:28:2,0:28:2].shape # batch_size, chanel, H(隔行采样), W(隔行采样)
# start : end : steps

torch.Size([4, 3, 14, 14])

In [14]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

# select by specific index

In [16]:
a.shape

torch.Size([4, 3, 28, 28])

In [17]:
a.index_select(0,torch.tensor([0,2])).shape # 对第0个维度的0，1张图片进行索引

torch.Size([2, 3, 28, 28])

In [18]:
a.index_select(1,torch.tensor([1,2])).shape # 四张图片只取两个通道

torch.Size([4, 2, 28, 28])

对于index_select函数，第二个参数不能直接给list，要将之转换为tensor才可以

In [19]:
a.index_select(2,torch.arange(28)).shape # 取[0,28)

torch.Size([4, 3, 28, 28])

In [20]:
a.index_select(2,torch.arange(8)).shape # 取[0,7)

torch.Size([4, 3, 8, 28])

# ... (这不是语气，表示任意多的维度)

In [21]:
a.shape

torch.Size([4, 3, 28, 28])

In [22]:
a[...].shape # 在这里代表4个：

torch.Size([4, 3, 28, 28])

In [23]:
a[0,...].shape # 在这里代表3个：

torch.Size([3, 28, 28])

In [24]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [25]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

# select by mask(不推荐用，因为会把数据打平)

In [29]:
x = torch.randn(3,4)
x

tensor([[-0.0704, -0.9625,  0.3872, -1.1956],
        [-0.6052,  0.5082,  1.0785,  1.0886],
        [ 0.4051, -1.0605, -0.4139, -0.8271]])

In [30]:
mask = x.ge(0.5) # 检查哪个元素大于0.5
mask

tensor([[False, False, False, False],
        [False,  True,  True,  True],
        [False, False, False, False]])

In [31]:
torch.masked_select(x, mask)  # 选出大于0.5的元素

tensor([0.5082, 1.0785, 1.0886])

### 之所以打平是因为>0.5的元素个数是根据内容才能确定的

In [32]:
torch.masked_select(x, mask).shape # dim为1，长度不定

torch.Size([3])

# select by flatten index

In [34]:
src=torch.tensor([[4,3,5],
                 [6,7,8]])

In [35]:
torch.take(src,torch.tensor([0,2,5])) # take会先将tensor打平，从[2,3]变为[5]，([4,3,5],[6,7,8]) -> ([4,3,5,6,7,8])

tensor([4, 5, 8])