In [1]:
import torch
import numpy as np

# import from numpy

In [3]:
a=np.array([2,3.3])

In [4]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [5]:
a=np.ones([2,3])

In [6]:
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# import from list

In [9]:
torch.tensor([2.,3.2]) # tensor与Tensor有区别

tensor([2.0000, 3.2000])

tensor：以现有的参数为数据

Tensor：以shape作为数据，生成对应形状的矩阵

In [10]:
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

以后直接传data时就用tensor，Tensor用来传shape，并且将Tensor写成FloatTensor,以免混淆

In [13]:
torch.tensor([[2.,3.2],[1.,22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

# 生成未初始化的数据

torch.empty()

torch.FloatTensor(d1,d2,d3)

torch.IntTensor(d1,d2,d3)

一般用这三个方法来初始化

In [17]:
torch.empty(1)

tensor([-6.5663e-09])

In [18]:
torch.Tensor(2,3)

tensor([[-6.5663e-09,  4.5902e-41,  1.6601e-35],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [19]:
torch.IntTensor(2,3)

tensor([[          0,           0,          81],
        [          0, -1310614304,       32757]], dtype=torch.int32)

In [20]:
torch.FloatTensor(2,3)

tensor([[1.6460e-35, 0.0000e+00, 1.6696e-35],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])

初始化完后这只是作为一个容器，后面记得覆盖掉，不然会有问题

# 设置默认数据类型

In [21]:
torch.tensor([1.2,3]).type() # pytorch默认是torch.FloatTensor

'torch.FloatTensor'

In [22]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [23]:
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

增强学习一般用double，其他一般用float

# rand/rand_like, randint

In [24]:
torch.rand(3,3) # rand（均匀分布）生成0-1之间的数字（不包括1）

tensor([[0.3405, 0.1139, 0.2377],
        [0.4325, 0.2926, 0.2182],
        [0.3808, 0.5611, 0.4872]])

In [25]:
a = torch.rand(3,3)

In [26]:
torch.rand_like(a) # 生成与a形状相同的矩阵

tensor([[0.7200, 0.7088, 0.0418],
        [0.6283, 0.4629, 0.7757],
        [0.5133, 0.1704, 0.6988]])

In [28]:
torch.randint(1,10,[3,3]) # (最小值，最大值，【矩阵】) ，该方法生成的是整数

tensor([[2, 6, 2],
        [5, 5, 9],
        [4, 9, 8]])

# randn（正态分布）

In [2]:
torch.randn(3,3)

tensor([[-0.2159, -0.3605,  0.4127],
        [-1.2786,  0.6666, -0.2773],
        [ 0.8413, -0.4487,  0.9008]])

In [4]:
torch.normal(mean=torch.full([10],0.),std=torch.arange(1,0,-0.1))  # 自定义均值和方差
# torch.full([10],0.)生成长度为10但都为0的向量；std=torch.arange(1,0,-0.1)方差1~0逐渐减小

tensor([-0.3060,  1.0070, -1.2464, -0.5778,  0.9589,  0.0659, -0.0091,  0.1987,
         0.0905,  0.1471])

torch.normal(mean均值，std方差)

# full (把tensor全部赋值为1个元素)

full（shape, val）

In [5]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [6]:
torch.full([],7)

tensor(7)

In [7]:
torch.full([],7.)

tensor(7.)

In [8]:
torch.full([1],7)

tensor([7])

In [9]:
torch.full([1],7.)

tensor([7.])

# arange/range

In [10]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.range(0,10)

/tmp/ipykernel_4864/497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# linspace/logspace (在arange里第三个参数是步长，在这里是数量)

## linspace 生成等差数列

In [13]:
torch.linspace(0,10,steps=4) # 从0~10等分地切4份

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [14]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [15]:
torch.linspace(0,10,steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## logspace 生成以val1~val2为指数、10为底数的数列，第三个参数为指数的步长

In [16]:
torch.logspace(0,1,steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

In [17]:
torch.logspace(0,-1,steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

# ones/zeros/eye (eye:单位矩阵)

In [18]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
a = torch.zeros(3,3)

In [22]:
torch.ones_like(a) # 往里传的是shape

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# randperm（随机打散）

In [23]:
torch.randperm(10)  # 生成0~10的随机索引

tensor([7, 9, 1, 8, 3, 5, 6, 4, 2, 0])

In [24]:
a=torch.rand(2,3)
b=torch.rand(2,2)
idx=torch.randperm(2)

In [25]:
idx

tensor([1, 0])

In [27]:
a[idx]

tensor([[0.4437, 0.8685, 0.0322],
        [0.0647, 0.2373, 0.6999]])

In [28]:
b[idx]

tensor([[0.5307, 0.4555],
        [0.9082, 0.1322]])

### a与b用同一个种子（idx）可在打乱时进行一个协同

In [29]:
a,b

(tensor([[0.0647, 0.2373, 0.6999],
         [0.4437, 0.8685, 0.0322]]),
 tensor([[0.9082, 0.1322],
         [0.5307, 0.4555]]))